### PR TITLE
Dude4linux's: update confconsole for v15.1

### PR DESCRIPTION
**Pull request by JedMeister**
This PR fixes the merge conflicts in #25.

### CODE REVIEW

**Review by OnGle — COMMENTED** [review]
Code looks good to me, on face value. I'm going to quickly test this live and make sure everything works as expected.

**Review by OnGle — APPROVED** [review]
No regressions, seems to behave as expected. My only note is that `systemctl restart networking` when changing the hostname is a pretty expensive operation which "may" kick users off their ssh or cause other weird things.

Since it's slow, there's no immediate way to discern whether your ssh connection has died or whether you're waiting for network restart. I suggest an additional intermediate screen to show the user "something" is happening.

**Comment by JedMeister** [comment]
@OnGle 
>My only note is that systemctl restart networking when changing the hostname is a pretty expensive operation which "may" kick users off their ssh or cause other weird things.
>
>Since it's slow, there's no immediate way to discern whether your ssh connection has died or whether you're waiting for network restart. I suggest an additional intermediate screen to show the user "something" is happening (as a future feature)

Hmm, yeah good point!

Although considering the points you raise, I'm actually thinking that perhaps we should have a confirmation (i.e. at least an "ok" or better still, a "yes"/"no") dialog before it does the network restart?!

**Comment by JedMeister** [comment]
Ok so let's add in the confirmation screen and merge this. Can you take care of that please @OnGle?

**Pull request merged**
